First Iteration
adwski/vidi pull request #1
Opened 2024-01-08 16:45 UTC by adwski

Bare minimum of functions for MVP

2024-01-23 21:13 UTC, s-shpak requested changes
Все круто, есть несколько минорных комментов. Я еще не запускал локально приложение, тебе осталось добавить какие-то фичи?

2024-01-23 21:13 UTC, s-shpak commented on internal/api/middleware/middleware.go
> +	e.Use(middleware.Recover())
Потенциально, паника может возникнуть и в middleware, потому я посоветовал зарегистрировать этот обработчик первым

2024-01-23 21:13 UTC, s-shpak commented on internal/api/store/migrate.go
> +func runMigrations(dsn string, migrationsDir *embed.FS) (bool, error) {
Мне не очень нравится сигнатура этой функции. Почему бы просто не возвращать ошибку и не проверять ее?

2024-01-23 21:13 UTC, s-shpak commented on internal/api/user/auth/auth.go
> +	SessionContextKey = "vUser"
не стоит экспортировать эту константу + для сохранения значений в контексте стоит использовать iota: https://splice.com/blog/iota-elegant-constants-golang/

2024-01-23 21:13 UTC, s-shpak commented on internal/api/user/store/store.go
> +	// TODO I dunno if manual salting is helping anything here
Нет, при использовании `bcrypt` это не требуется

2024-01-23 21:13 UTC, s-shpak commented on internal/api/video/model/status.go
> +// TODO: How these statuses will map to DB enums? (or don't use enums may be?)
Я бы не стал использовать `enum`: несмотря на то, что есть риск записать неверное значение в таблицу, если запись происхдит только из приложения, `enum` можно не использовать. Преимущество - отстутствие бизнес-логики в БД

2024-01-23 21:13 UTC, s-shpak commented on internal/api/video/model/status.go
> +	VideoStatusError = iota - 1
```suggestion
	VideoStatusError Status = iota - 1
```

2024-01-23 21:13 UTC, s-shpak commented on internal/api/video/store/migrations/00001_init.up.sql
> +CREATE UNIQUE INDEX videos_id On videos (id);
```suggestion
CREATE UNIQUE INDEX videos_id ON videos (id);
```

2024-01-23 21:13 UTC, s-shpak commented on internal/media/processor/mpd.go
> +				// TODO Last segment duration most probably will not be equal to segmentDuration
Это надо протестить. Я бы не стал полагаться на логику на стороне клиента.

2024-01-23 21:13 UTC, s-shpak commented on internal/media/processor/process.go
> +	// TODO This approach reads whole file into memory, should use lazy read in the future
Да, это хорошее улучшение на будущее

2024-01-23 21:41 UTC, adwski commented
> Все круто, есть несколько минорных комментов. Я еще не запускал локально приложение, тебе осталось добавить какие-то фичи?

Нет, по фичам всё. Главное сейчас тесты. Если успею, добавлю сваггер

2024-01-29 21:13 UTC, adwski commented on internal/media/processor/mpd.go
> +				// TODO Last segment duration most probably will not be equal to segmentDuration
На данный момент видео проигрывается в Chrome без compliance ошибок. На точную проверку по стандарту и коду reference-плеера потребуется дополнительное время.

2024-01-29 21:14 UTC, adwski commented on internal/api/video/model/status.go
> +// TODO: How these statuses will map to DB enums? (or don't use enums may be?)
В echo контексте ключи могут быть только строками

2024-01-31 20:45 UTC, adwski commented on internal/api/user/auth/auth.go
> +	SessionContextKey = "vUser"
В echo контексте ключи могут быть только строками. Саму константу сделал неэкспортируемой

2024-02-05 10:29 UTC, s-shpak requested changes

2024-02-05 10:29 UTC, s-shpak commented on pkg/config/config_test.go
> +			err: "must not end with",
Почему бы не добавить в тест точный текст ошибки ?

2024-02-05 10:29 UTC, s-shpak commented on internal/api/video/store/store.go
> +		err = model.ErrNotFound
Ты теряешь ошибку здесь, почему бы не `return nil, fmt.Errorf("%w: %w", err, model.ErrNotFound)` ?

2024-02-05 18:05 UTC, adwski commented on pkg/config/config_test.go
> +			err: "must not end with",
Согласен. пофиксил

2024-02-05 18:05 UTC, adwski commented on internal/api/video/store/store.go
> +		err = model.ErrNotFound
Тут я ошибся, нужно просто обработать pg ошибку. Пофиксил

2024-02-07 09:59 UTC, s-shpak approved these changes

2024-02-08 10:07 UTC, merged